<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public $countries = [
        'Cyprus',
        'Netherlands',
        'Switzerland',
        'United States',
        'United Kingdom',
        'Ireland',

        'Aruba',
        'Afghanistan',
        'Angola',
        'Albania',
        'Andorra',
        'United Arab Emirates',
        'Argentina',
        'Armenia',
        'American Samoa',
        'Antigua and Barbuda',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Burundi',
        'Belgium',
        'Benin',
        'Burkina Faso',
        'Bangladesh',
        'Bulgaria',
        'Bahrain',
        'Bahamas, The',
        'Bosnia and Herzegovina',
        'Belarus',
        'Belize',
        'Bermuda',
        'Bolivia',
        'Brazil',
        'Barbados',
        'Brunei Darussalam',
        'Bhutan',
        'Botswana',
        'Central African Republic',
        'Canada',
        //   'Switzerland',
        'Channel Islands',
        'Chile',
        'China',
        'Cote d\'Ivoire',
        'Cameroon',
        'Congo, Dem. Rep.',
        'Congo, Rep.',
        'Colombia',
        'Comoros',
        'Cabo Verde',
        'Costa Rica',
        'Cuba',
        'Curacao',
        'Cayman Islands',
        //   'Cyprus',
        'Czech Republic',
        'Germany',
        'Djibouti',
        'Dominica',
        'Denmark',
        'Dominican Republic',
        'Algeria',
        'Ecuador',
        'Egypt, Arab Rep.',
        'Eritrea',
        'Spain',
        'Estonia',
        'Ethiopia',
        'Finland',
        'Fiji',
        'France',
        'Faroe Islands',
        'Micronesia, Fed. Sts.',
        'Gabon',
        //   'United Kingdom',
        'Georgia',
        'Ghana',
        'Gibraltar',
        'Guinea',
        'Gambia, The',
        'Guinea-Bissau',
        'Equatorial Guinea',
        'Greece',
        'Grenada',
        'Greenland',
        'Guatemala',
        'Guam',
        'Guyana',
        'Hong Kong SAR, China',
        'Honduras',
        'Croatia',
        'Haiti',
        'Hungary',
        'Indonesia',
        'Isle of Man',
        'India',
        //   'Ireland',
        'Iran, Islamic Rep.',
        'Iraq',
        'Iceland',
        'Israel',
        'Italy',
        'Jamaica',
        'Jordan',
        'Japan',
        'Kazakhstan',
        'Kenya',
        'Kyrgyz Republic',
        'Cambodia',
        'Kiribati',
        'St. Kitts and Nevis',
        'Korea, Rep.',
        'Kuwait',
        'Lao PDR',
        'Lebanon',
        'Liberia',
        'Libya',
        'St. Lucia',
        'Liechtenstein',
        'Sri Lanka',
        'Lesotho',
        'Lithuania',
        'Luxembourg',
        'Latvia',
        'Macao SAR, China',
        'St. Martin (French part)',
        'Morocco',
        'Monaco',
        'Moldova',
        'Madagascar',
        'Maldives',
        'Mexico',
        'Marshall Islands',
        'Macedonia, FYR',
        'Mali',
        'Malta',
        'Myanmar',
        'Montenegro',
        'Mongolia',
        'Northern Mariana Islands',
        'Mozambique',
        'Mauritania',
        'Mauritius',
        'Malawi',
        'Malaysia',
        'Namibia',
        'New Caledonia',
        'Niger',
        'Nigeria',
        'Nicaragua',
        //   'Netherlands',
        'Norway',
        'Nepal',
        'Nauru',
        'New Zealand',
        'Oman',
        'Pakistan',
        'Panama',
        'Peru',
        'Philippines',
        'Palau',
        'Papua New Guinea',
        'Poland',
        'Puerto Rico',
        'Korea, Dem. Peoples Rep.',
        'Portugal',
        'Paraguay',
        'West Bank and Gaza',
        'French Polynesia',
        'Qatar',
        'Romania',
        'Russian Federation',
        'Rwanda',
        'Saudi Arabia',
        'Sudan',
        'Senegal',
        'Singapore',
        'Solomon Islands',
        'Sierra Leone',
        'El Salvador',
        'San Marino',
        'Somalia',
        'Serbia',
        'South Sudan',
        'Sao Tome and Principe',
        'Suriname',
        'Slovak Republic',
        'Slovenia',
        'Sweden',
        'Swaziland',
        'Sint Maarten (Dutch part)',
        'Seychelles',
        'Syrian Arab Republic',
        'Turks and Caicos Islands',
        'Chad',
        'Togo',
        'Thailand',
        'Tajikistan',
        'Turkmenistan',
        'Timor-Leste',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Tuvalu',
        'Taiwan, China',
        'Tanzania',
        'Uganda',
        'Ukraine',
        'Uruguay',
        //   'United States',
        'Uzbekistan',
        'St. Vincent and the Grenadines',
        'Venezuela, RB',
        'British Virgin Islands',
        'Virgin Islands (U.S.)',
        'Vietnam',
        'Vanuatu',
        'Samoa',
        'Kosovo',
        'Yemen, Rep.',
        'South Africa',
        'Zambia',
        'Zimbabwe',
    ];

    public function run()
    {
        foreach ($this->countries as $country){
            DB::table('countries')->insert([
                'name' => $country,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
